# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test Showcase

on:
  push:
    paths:
      - "app/client-next-ts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --frozen-lockfile
        working-directory: ./app/client-next-ts
      - name: Build
        run: npm run build
        working-directory: ./app/client-next-ts
      - name: Run tests
        run: npm run test
        working-directory: ./app/client-next-ts
