name: Wait and Verify Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  # Job: Wait for Amplify deployment + Run health check
  health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd app/client-next-ts
          npm ci

      - name: Install Playwright
        run: |
          cd app/client-next-ts
          npx playwright install --with-deps chromium

      - name: Wait for Amplify deployment
        run: |
          echo "⏳ Waiting for Amplify to auto-deploy from amplify.yml..."
          echo "This gives Amplify time to build and deploy the changes"
          sleep 240  # 4 minutes - adjust based on your deployment time

      - name: Run health check
        id: health-check
        run: |
          cd app/client-next-ts
          echo "🔍 Running health check against deployed demo..."
          npm run health-check
        env:
          TARGET_URL: "https://embedded-finance-dev.com/sellsense-demo?scenario=Seller+with+Limited+DDA&view=wallet"

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: health-check-screenshots
          path: app/client-next-ts/health-check-*.png
          retention-days: 7

      - name: Health check summary
        if: always()
        run: |
          echo "## 🏥 Health Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Target URL:** https://embedded-finance-dev.com/sellsense-demo" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ **Health check passed successfully!**" >> $GITHUB_STEP_SUMMARY
            echo "- Demo page loaded correctly" >> $GITHUB_STEP_SUMMARY
            echo "- MSW is functioning properly" >> $GITHUB_STEP_SUMMARY
            echo "- No critical errors detected" >> $GITHUB_STEP_SUMMARY
            echo "- Transactions list is accessible" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**PR Status:** Ready to merge ✅" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Health check failed!**" >> $GITHUB_STEP_SUMMARY
            echo "- Check the logs above for details" >> $GITHUB_STEP_SUMMARY
            echo "- Screenshots have been uploaded as artifacts" >> $GITHUB_STEP_SUMMARY
            echo "- Review the error details and fix the issues" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**PR Status:** Blocked until health check passes ❌" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Update PR status
        if: github.event_name == 'pull_request'
        run: |
          echo "🔄 Updating PR status..."

          if [ "${{ steps.health-check.outcome }}" == "success" ]; then
            echo "✅ Health check passed - PR is ready to merge"
            # You could add more status updates here
            # gh pr checks "${{ github.event.pull_request.number }}" --add-status "Health Check" success "Deployment verified"
          else
            echo "❌ Health check failed - PR needs attention"
            echo "This will block the PR from being merged"
            exit 1  # This will fail the workflow and block PR
          fi
